name: CI Pipeline

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      # Checkout frontend repository
      - name: Checkout frontend repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build frontend Docker image
      - name: Build frontend Docker image
        run: |
          cd my-blog
          docker build -t my-blog-frontend .

      # Run frontend unit tests
      - name: Run frontend unit tests
        run: |
          docker run --rm my-blog-frontend npm test

      # Checkout backend repository
      - name: Checkout backend repository
        uses: actions/checkout@v2
        with:
          repository: mywyau/tarnish
          path: backend-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      # Build backend Docker image
      - name: Build backend Docker image
        run: |
          cd backend-repo
          docker build -t my-blog-backend .

      # Run backend Docker container
      - name: Run backend Docker container
        run: |
          docker run -d -p 8080:8080 --name backend my-blog-backend

      # Run frontend Docker container
      - name: Run frontend Docker container
        run: |
          docker run -d -p 3000:3000 --name frontend my-blog-frontend

      # Wait for services to be ready
      - name: Wait for services to be ready
        run: |
          sleep 15  # Adjust the wait time if necessary

      - name: Checkout selenium tests repository
        uses: actions/checkout@v2
        with:
          repository: mywyau/concurrent_ui-tests
          token: ${{ secrets.GITHUB_TOKEN }}   
          
      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-env --version
  
      - name: Set up Nix shell
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-shell --run "echo 'Running inside Nix shell!'"
  
      - name: Install chromedriver via Nix
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-env -iA nixpkgs.chromedriver
  
      - name: Set up PATH for chromedriver
        run: |
          echo "/home/runner/.nix-profile/bin" >> $GITHUB_PATH
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          which chromedriver
  
      - name: Install dependencies for Selenium tests
        run: |
          sbt compile
  
      - name: Run Selenium Browser tests
        run: |
          sbt -Denvironment=githubActions -Dheadless=true test    

      # Clean up
      - name: Clean up
        run: |
          docker stop frontend backend
          docker rm frontend backend
          docker rmi my-blog-frontend my-blog-backend
