name: CI Pipeline

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/my-blog/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd my-blog
          npm install

      - name: Run unit tests
        run: |
          cd my-blog
          npm test

  browser-tests:
    runs-on: ubuntu-latest
    needs: unit-tests  # This ensures that browser-tests job will only run if unit-tests job passes

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout selenium tests repository
        uses: actions/checkout@v2
        with:
          repository: owner/selenium-tests-repository
          path: selenium-tests
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd selenium-tests
          npm install

      - name: Run browser tests
        run: |
          cd selenium-tests
          npm run test:browser
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub
