name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      # - qa
      # - staging
      # - production
  pull_request:
    branches:
      - main
      # - qa
      # - staging
      # - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start SSH agent
      run: eval $(ssh-agent -s)
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH }}

    - name: Add EC2 host to known_hosts
      run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ec2-18-134-249-218.eu-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts
      shell: bash  

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    # - name: Install dependencies
    #   run: npm install

    # - name: Compile TypeScript
    #   run: npm run build

    # - name: Run code
    #   run: npm start
      
    # - name: Run tests
    #   run: npm test

    # - name: Deploy to EC2
    #   run: |
    #     ssh ec2-user@ec2-18-134-249-218.eu-west-2.compute.amazonaws.com 'cd ~/my-project/ci-cd && git pull origin main && npm install && npm run build && pm2 restart all'

    - name: Install TypeScript
      run: npm install -g typescript

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run build

    - name: Run code
      run: npm start
      
    - name: Run tests
      run: npm test

    - name: Deploy to EC2
      run: |
        ssh ec2-user@ec2-18-134-249-218.eu-west-2.compute.amazonaws.com '
          cd ~/my-project/ci-cd &&
          git pull origin main &&
          npm install &&
          npm run build &&
          pm2 restart all
        '