name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      # - qa
      # - staging
      # - production
  pull_request:
    branches:
      - main
      # - qa
      # - staging
      # - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start SSH agent
      run: eval $(ssh-agent)
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ec2-18-134-249-218.eu-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run build

    - name: Run code
      run: npm start
      
    - name: Run tests
      run: npm test

    # - name: Deploy to EC2
    #   run: |
    #     scp -r ./* ec2-user@ec2-18-134-249-218.eu-west-2.compute.amazonaws.com:/path/to/destination
    #     ssh ec2-user@<your-ec2-ip> 'bash -s' < deploy_script.sh

    - name: Deploy to EC2
      run: |
          ssh ec2-user@ec2-18-134-249-218.eu-west-2.compute.amazonaws.com 'cd ~/my-project/ci-cd && git pull origin main

  # deploy_qa:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/qa'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Mock QA Deployment
  #     run: echo "Deploying to QA environment..."
      
  # deploy_staging:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/staging'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Mock Staging Deployment
  #     run: echo "Deploying to Staging environment..."

  # deploy_production:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/production'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Mock Production Deployment
  #     run: echo "Deploying to Production environment..."
