name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      # - qa
      # - staging
      # - production
  pull_request:
    branches:
      - main
      # - qa
      # - staging
      # - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run build

    - name: Run code
      run: npm start
      
    - name: Run tests
      run: npm test

  # deploy_qa:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/qa'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Mock QA Deployment
  #     run: echo "Deploying to QA environment..."
      
  # deploy_staging:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/staging'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Mock Staging Deployment
  #     run: echo "Deploying to Staging environment..."

  # deploy_production:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/production'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Mock Production Deployment
  #     run: echo "Deploying to Production environment..."
