name: CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/my-blog/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd my-blog
          npm install

      - name: Run unit tests
        run: |
          cd my-blog
          npm test

      # - name: Build the project
      #   run: |
      #     cd my-blog
      #     npm run build

      
      # - name: Configure Git for deployment
      #   run: |
      #     git config --global user.email "47248104+mywyau@users.noreply.github.com"
      #     git config --global user.name "mywyau"    

      # - name: Deploy to GitHub Pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided to the workflow
      #   run: |
      #     cd my-blog
      #     npm run deploy

      # - name: Check deployment status
      #   run: |
      #     echo "Checking if deployment was successful..."
      #     curl -s -o /dev/null -w "%{http_code}" https://{mywyau}.github.io/ | grep 200

  selenium-tests:
    runs-on: ubuntu-latest
    needs: build-and-test

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # - name: Install dependencies for React app
      #   run: |
      #     cd my-blog
      #     npm install

      # - name: Start React app
      #   run: |
      #     cd my-blog
      #     nohup npm start > nohup.out 2>&1 &
      #   env:
      #     CI: true

      # - name: Wait for React app to be available
      #   run: |
      #     echo "Waiting for React app to start..."
      #     for i in {1..30}; do
      #       curl -sSf http://localhost:3000/ && break
      #       echo "Waiting..."
      #       sleep 5
      #     done

      # - name: Display React app logs
      #   run: |
      #     cat my-blog/nohup.out

      - name: Checkout selenium tests repository
        uses: actions/checkout@v2
        with:
          repository: mywyau/concurrent_ui-tests
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-env --version

      - name: Set up Nix shell
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-shell --run "echo 'Running inside Nix shell!'"

      - name: Install chromedriver via Nix
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-env -iA nixpkgs.chromedriver

      - name: Set up PATH for chromedriver
        run: |
          echo "/home/runner/.nix-profile/bin" >> $GITHUB_PATH
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          which chromedriver

      - name: Install dependencies for Selenium tests
        run: |
          sbt compile

      - name: Run browser tests
        run: |
          sbt test

      - name: Clean up my-blog directory
        run: |
          pkill -f "npm start" || true
          sleep 10  # Give some time for processes to stop
          rm -rf my-blog || true
