# .github/workflows/ci.yml

name: run unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: |
          cd my-blog
          npm install
          npm install --save-dev @types/jest
          npm install --save-dev @testing-library/react @testing-library/jest-dom @types/testing-library__jest-dom
          npm install --save-dev jest-environment-jsdom 
          npm test


      # - run: |
      #     cd my-blog
      #     npm test
