name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code   
      uses: actions/checkout@v3

    - name: Navigate to app
      run: cd ~/my-project/ci-cd/my-blog
    
    - name: Install TypeScript
      run: npm install -g typescript  

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run build

    - name: Run code
      run: npm start
      
    - name: Run tests
      run: npm test